from transformers import T5Tokenizer, T5ForConditionalGeneration



# Initialised Flask app --TODO




# Loaded T5 tokenizer and model

MODEL_NAME = "t5-small"
tokenizer = T5Tokenizer.from_pretrained(MODEL_NAME);
model = T5ForConditionalGeneration.from_pretrained(MODEL_NAME);



# Extract YT video ID  TODO



# Transcript Summarizer

def transcript_summarizer(transcript_text: str) -> str:
    
    if not transcript_text or not transcript_text.strip():  
        return ""
    
    input_text = "summarize: " + transcript_text

    input_ids = tokenizer.encode(              # CONVERTS WORDS TO TOKENS
        input_text,
        return_tensors="pt",                   # gives the result in a PYTorch readable format
        max_length=1024,                       # AI reads atmost 1024 words-pieces at one time
        truncation=True                        # if the text is too long, the extra part is cut (avoids crashing of AI)
    )

    summary_ids = model.generate(              # THE MODEL GENERATES THE SUMMARY
        input_ids,
        max_length=150,                        # the summary cannot be longer than 150 words
        min_length=40,                         # the summary should be aleast 40 words
        length_penalty=2.0,                    # AI can make the summary short and neat
        num_beams=4,                           # The AI tries 4 different ways to write the summary
        early_stopping=True                    # stop thinking once a good summary is found
    )

    summary = tokenizer.decode(                # TURNS BACK TOKENS TO WORDS
        summary_ids[0],                        # the summary generated by the model
        skip_special_tokens=True               # remove extra symbols
    )
    return summary



# REST API Endpoint TODO



# Run Flask Application TODO