from transformers import T5Tokenizer, T5ForConditionalGeneration
from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled, NoTranscriptFound
from flask import Flask, request, jsonify
from flask_cors import CORS


# Flask app initialisation
app = Flask(__name__)
CORS(app)


@app.route("/", methods=["GET"])
def home():
    return jsonify({
        "message": "YouTube Transcript Summarizer Backend is running"
    })


# Loaded T5 tokenizer and model
MODEL_NAME = "t5-small"
tokenizer = T5Tokenizer.from_pretrained(MODEL_NAME);
model = T5ForConditionalGeneration.from_pretrained(MODEL_NAME);



# Extract YT video ID 
def get_transcript(video_id: str) -> str:
    try:
        transcript_data = YouTubeTranscriptApi.get_transcript(video_id)
        return " ".join(item["text"] for item in transcript_data)

    except TranscriptsDisabled:
        raise Exception("Transcripts are disabled for this video")

    except NoTranscriptFound:
        raise Exception("No transcript found for this video")

    except Exception as e:
        raise Exception(str(e))




# Transcript Summarizer
def transcript_summarizer(transcript_text: str) -> str:
    
    if not transcript_text or not transcript_text.strip():  
        return ""
    
    input_text = "summarize: " + transcript_text

    input_ids = tokenizer.encode(              # CONVERTS WORDS TO TOKENS
        input_text,
        return_tensors="pt",                   # gives the result in a PYTorch readable format
        max_length=1024,                       # AI reads atmost 1024 words-pieces at one time
        truncation=True                        # if the text is too long, the extra part is cut (avoids crashing of AI)
    )

    summary_ids = model.generate(              # THE MODEL GENERATES THE SUMMARY
        input_ids,
        max_length=150,                        # the summary cannot be longer than 150 words
        min_length=40,                         # the summary should be aleast 40 words
        length_penalty=2.0,                    # AI can make the summary short and neat
        num_beams=4,                           # The AI tries 4 different ways to write the summary
        early_stopping=True                    # stop thinking once a good summary is found
    )

    summary = tokenizer.decode(                # TURNS BACK TOKENS TO WORDS
        summary_ids[0],                        # the summary generated by the model
        skip_special_tokens=True               # remove extra symbols
    )
    return summary



@app.route("/api/summarize", methods=["POST"])
def summarize_api():
    data = request.get_json()
    video_id = data.get("videoId")

    if not video_id:
        return jsonify({"error": "videoId is required"}), 400

    try:
        transcript = get_transcript(video_id)
        summary = transcript_summarizer(transcript)
    except Exception as e:
        return jsonify({
            "error": "Transcript not available",
            "details": str(e)
        }), 400

    return jsonify({
        "videoId": video_id,
        "summary": summary
    })



# Run Flask Application
if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=True)
